namespace WeatherForecastLTMRabbitMongoSeq
{
    public class TraceLogService
    {
        private readonly MongoDbContext _tracingContext;
        private readonly ILogger<TraceLogService> _logger;

        public TraceLogService(MongoDbContext tracingContext, ILogger<TraceLogService> logger)
        {
            _tracingContext = tracingContext;
            _logger = logger;
        }

        public async Task LogTraceAsync(string message, LogLevel level = LogLevel.Information, CancellationToken cancellationToken = default)
        {
            var traceLog = new TraceLog
            {
                Message = message,
                Level = level.ToString(),
                // Id will be automatically generated by MongoDB
            };

            try
            {
                await _tracingContext.AddTraceLogAsync(traceLog, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to log trace to MongoDB");
            }
        }
    }
}
